### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by knuxify** [knuxify/pyBotB#1]
## API completeness

See https://battleofthebits.com/api/v1/documentation/index.

* [x] Battle (basics done, needs `current`, `entries_by_format`, `list_by_date`, `list_by_month`
  * [x] `current`
  * [x] `list_by_date`/`list_by_month` 
  * [x] API for downloading bitpack(s)? Remember about advent calendar handling...
* [x] BotBr
  * [x] Fix favorite get functions (check if entry get is correct too, would probably be better to replace it with entry list + IN_SUBQUERY too)
  * [x] Badge progress fetch
  * [x] Country flag fetch
  * [x] Fetch LEVELS variable at runtime (available as `BotB.botbr_levels` cached property)
* [x] `botbr_stats`
* [x] `daily_stats`
* [x] Entry
* [x] Favorite
* [x] Firki (also finish the relevant python implementation)
* [x] Format
* [x] Group thread
* [x] Lyceum article
* [x] Palette
* [x] Playlist + playlist_to_entry
* [x] Tag
  * [x] Tag cloud
* [x] Spriteshit version

## Code

* [x] Fix dataclasses not getting converted correctly in unroll_payload, this breaks Entry repr...
* [x] Move dataclasses to separate .py file
* [x] Fix user agent
* [x] Add offset option to PaginatedList

## Userbot features

...are being scrapped and will be moved out to their own separate library. Not sure if I want to open-source that just yet (too much potential for abuse...)

## Library

* [x] Set up CI
* Write docs:
  * [ ] Write docs index
  * [x] Write BotB API intro docs
  * [ ] Write some examples
* [x] Publish docs... somewhere (readthedocs.io or some self-hosted solution (GH Pages)? How do we achieve versioning?)
